---
  - name: "pentest"
    box:  ubuntu/trusty64
    autostart: true
    communicator: ssh
    ip:    10.0.0.10
    cpu:   4
    memory: 4096
    host:  pentest
    ports:
        - { id: "web", guest: 80, host: 8080, protocol: tcp, host_ip: 127.0.0.1 }
    aliases:
        - pentest.localhost.com
    folders:
        - { src: './src', target: '/home/vagrant/src' }
    provision-commands:
        - { command: 'DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get -y install build-essential checkinstall && apt-get -y install libssl-dev gnupg wget ca-certificates apt-transport-https', privileged: true }
        - { command: 'DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:webupd8team/java -y && apt-get -y update && echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections', privileged: true }
        - { command: 'DEBIAN_FRONTEND=noninteractive apt-get -y install oracle-java8-installer && apt-get -y install oracle-java8-set-default', privileged: true }
        - { command: 'DEBIAN_FRONTEND=noninteractive apt-get -y  install samba dnsutils && cp /vagrant/smb.conf /etc/samba/smb.conf &&  (echo vagrant; echo vagrant) | smbpasswd -a -s vagrant && service smbd restart', privileged: true }

    provision-docker: true
    provision-docker-compose: 
        - { yml: '/vagrant/src/base/docker-compose.yml', env: {}, rebuild: false, run: 'always' }    